version: '3'
services:
  node:
    image: "node:12"
    user: "node"
    container_name: mistpipe
    restart: always
    working_dir: /home/node/app
    volumes:
      - ./app:/home/node/app
    ports:
      - "3000:3001"
    environment:
      - "NODE_ENV=production"
    command: "node server.js"
